language: python

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq -y update

install:
  - sudo deb http://qgis.org/debian vivid main
  - sudo deb-src http://qgis.org/debian vivid main
  - sudo gpg --keyserver keyserver.ubuntu.com --recv 3FF5FFCAD71472C4
  - sudo gpg --export --armor 3FF5FFCAD71472C4 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis python-qt4
  - sudo pip install nose2
  - sudo pip install nose_parameterized

script:
  - nosetests
