language: c++

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq -y update

install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository http://qgis.org/debian
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis python-qt4
  - sudo pip install nose2

script:
  - nose2
