language: python

sudo: false
dist: trusty

env:
  - QGIS_DOCKER_TAG=master
  - QGIS_DOCKER_TAG=3.0

script:
  - docker pull "qgis/qgis:${QGIS_DOCKER_TAG}"
  - docker run -v .:/root/qgissettingmanager "qgis/qgis:${QGIS_DOCKER_TAG}" nose2 -s /root/qgissettingmanager
