language: python

before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable  # for QGIS
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis python-qt4
  - sudo pip install nose2
  - sudo pip install nose_parameterized

script:
  - nosetests
