language: python

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq -y update

env:
  - QGIS_REPO=http://qgis.org/debian-nightly QGIS_BRANCH=master
  - QGIS_REPO=http://qgis.org/debian QGIS_BRANCH=release-2_14

install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis xvfb
  - sudo pip install nose2

script:
  - export PATH=/usr/bin:$PATH
  - curl -L https://github.com/qgis/QGIS/archive/${QGIS_BRANCH}.tar.gz | tar -xzC /tmp
  - sudo cp -r /tmp/QGIS-${QGIS_BRANCH}/python/PyQt/PyQt4 /usr/lib/python2.7/dist-packages/PyQt
  - test "${QGIS_BRANCH}" = "release-2_14" && sudo cp -r /tmp/QGIS-${QGIS_BRANCH}/python/testing /usr/lib/python2.7/dist-packages/qgis/testing
  - xvfb-run nose2
