language: python

sudo: false
dist: trusty

env:
  - QGIS_DOCKER_TAG=latest
  - QGIS_DOCKER_TAG=release-3_0

script:
  - docker pull "qgis/qgis:${QGIS_DOCKER_TAG}"
  - docker run -v $TRAVIS_BUILD_DIR/qgissettingmanager:/root/qgissettingmanager "qgis/qgis:${QGIS_DOCKER_TAG}" bash -c 'nose2-3 -s /root/qgissettingmanager'
